FROM python:3.12-slim

ENV API_URL="http://flies-detector-backend:8000"

RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN pip install --upgrade pip && \
    pip install fastapi uvicorn pillow numpy ultralytics python-multipart gradio

COPY ./code/yolo2class_pipeline/gradio_app.py ./gradio_app.py
COPY ./code/yolo2class_pipeline/fonts ./fonts

EXPOSE 7860

CMD ["python", "gradio_app.py"]