services:
  flies-detector-backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: flies-detector-backend
    networks:
      - flies-detector-network
    ports:
      - "8000:8000"

  flies-detector-frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: flies-detector-frontend
    networks:
      - flies-detector-network
    ports:
      - "7860:7860"
    depends_on:
      - flies-detector-backend

networks:
  flies-detector-network:
    driver: bridge 