name: flies
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - anyio=4.6.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - async-lru=2.0.4
  - attrs=24.2.0
  - babel=2.11.0
  - beautifulsoup4=4.12.3
  - blas=1.0
  - bleach=4.1.0
  - bottleneck=1.4.2
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.1.31
  - cairo=1.16.0
  - certifi=2024.12.14
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - comm=0.2.1
  - contourpy=1.3.1
  - cuda-cudart=12.4.127
  - cuda-cupti=12.4.127
  - cuda-libraries=12.4.1
  - cuda-nvrtc=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-opencl=12.6.77
  - cuda-runtime=12.4.1
  - cuda-version=12.6
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dbus=1.13.18
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - eigen=3.4.0
  - executing=0.8.3
  - expat=2.6.3
  - ffmpeg=4.2.2
  - filelock=3.13.1
  - fontconfig=2.14.2
  - fonttools=4.51.0
  - freetype=2.12.1
  - fsspec=2024.6.1
  - giflib=5.2.2
  - glib=2.78.4
  - glib-tools=2.78.4
  - gmp=6.2.1
  - gnutls=3.6.15
  - graphite2=1.3.14
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - h11=0.14.0
  - harfbuzz=4.3.0
  - hdf5=1.12.1
  - httpcore=1.0.2
  - httpx=0.27.0
  - huggingface_hub=0.24.6
  - icu=73.1
  - idna=3.7
  - importlib-metadata=8.5.0
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.27.0
  - ipywidgets=8.1.2
  - jedi=0.19.1
  - jinja2=3.1.4
  - jpeg=9e
  - json5=0.9.25
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.7.1
  - jupyter=1.0.0
  - jupyter-collaboration=3.0.1
  - jupyter-collaboration-ui=1.0.1
  - jupyter-docprovider=1.0.1
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.0
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.1
  - jupyter_server_fileid=0.9.2
  - jupyter_server_terminals=0.4.4
  - jupyter_server_ydoc=1.0.1
  - jupyter_ydoc=3.0.1
  - jupyterlab=4.2.5
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.10
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.40
  - lerc=3.0
  - libabseil=20240116.2
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcublas=12.4.5.8
  - libcufft=11.2.1.3
  - libcufile=1.11.1.6
  - libcups=2.4.2
  - libcurand=10.3.7.77
  - libcurl=8.9.1
  - libcusolver=11.6.1.9
  - libcusparse=12.3.1.170
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libev=4.33
  - libexpat=2.6.3
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.78.4
  - libgomp=14.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libllvm14=14.0.6
  - libnghttp2=1.57.0
  - libnpp=12.2.5.30
  - libnsl=2.0.1
  - libnvfatbin=12.6.77
  - libnvjitlink=12.4.127
  - libnvjpeg=12.3.1.117
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=17.0
  - libprotobuf=4.25.3
  - libsodium=1.0.18
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libvpx=1.7.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxcrypt=4.4.36
  - libxkbcommon=1.0.1
  - libxml2=2.13.5
  - libzlib=1.2.13
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpmath=1.3.0
  - mysql=8.4.0
  - nbclient=0.8.0
  - nbconvert=7.16.4
  - nbformat=5.10.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - nettle=3.7.3
  - networkx=3.2.1
  - notebook=7.2.2
  - notebook-shim=0.2.3
  - numexpr=2.10.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - opencv=4.10.0
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openldap=2.6.4
  - openssl=3.4.0
  - overrides=7.4.0
  - packaging=24.1
  - pandas=2.2.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre2=10.42
  - pexpect=4.8.0
  - pip=24.2
  - pixman=0.40.0
  - platformdirs=3.10.0
  - ply=3.11
  - prometheus_client=0.21.0
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py-cpuinfo=9.0.0
  - py-opencv=4.10.0
  - pycparser=2.21
  - pycrdt=0.10.6
  - pycrdt-websocket=0.15.1
  - pygments=2.15.1
  - pyparsing=3.2.0
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.12.2
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.20.0
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - python_abi=3.12
  - pytorch=2.5.1
  - pytorch-cuda=12.4
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyyaml=6.0.2
  - pyzmq=25.1.2
  - qt-main=5.15.2
  - qtconsole=5.6.0
  - qtpy=2.4.1
  - readline=8.2
  - referencing=0.30.2
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.6
  - safetensors=0.4.5
  - scipy=1.14.1
  - seaborn=0.13.2
  - send2trash=1.8.2
  - setuptools=75.1.0
  - sip=6.7.12
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.45.3
  - sqlite-anyio=0.2.3
  - stack_data=0.2.0
  - supervision=0.18.0
  - tbb=2021.8.0
  - terminado=0.17.1
  - timm=1.0.14
  - tinycss2=1.2.1
  - tk=8.6.14
  - torchaudio=2.5.1
  - torchtriton=3.1.0
  - torchvision=0.20.1
  - tornado=6.4.1
  - tqdm=4.66.5
  - traitlets=5.14.3
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024b
  - ultralytics=8.3.40
  - unicodedata2=15.1.0
  - urllib3=2.2.3
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.44.0
  - widgetsnbextension=4.0.10
  - x264=1!157.20191217
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - aim==3.26.1
      - aim-ui==3.26.1
      - aimrecords==0.0.7
      - aimrocks==0.5.2
      - aiofiles==24.1.0
      - alembic==1.14.0
      - annotated-types==0.7.0
      - appdirs==1.4.4
      - argcomplete==3.5.3
      - backports-weakref==1.0.post1
      - base58==2.0.1
      - black==24.10.0
      - blinker==1.9.0
      - boto3==1.35.76
      - botocore==1.35.76
      - cachetools==5.5.0
      - captum==0.7.0
      - click==8.1.7
      - colorama==0.4.6
      - cryptography==43.0.3
      - datamodel-code-generator==0.26.1
      - dnspython==2.7.0
      - easy-explain==0.5.0
      - email-validator==2.2.0
      - faker==33.3.1
      - fastapi==0.115.6
      - flask==2.3.3
      - genson==1.3.0
      - google-api-core==2.24.2
      - google-api-python-client==2.166.0
      - google-auth==2.38.0
      - google-auth-httplib2==0.2.0
      - googleapis-common-protos==1.69.2
      - greenlet==3.1.1
      - httplib2==0.22.0
      - ijson==3.3.0
      - inflect==5.6.2
      - isort==5.13.2
      - itsdangerous==2.2.0
      - jmespath==1.0.1
      - joblib==1.4.2
      - jsf==0.11.2
      - label-studio-sdk==1.0.10
      - lxml==5.3.0
      - mako==1.3.8
      - mypy-extensions==1.0.0
      - nltk==3.9.1
      - oauth2client==4.1.3
      - pathspec==0.12.1
      - piexif==1.1.3
      - pillow==10.4.0
      - pillow-heif==0.22.0
      - proto-plus==1.26.1
      - protobuf==6.30.2
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.10.3
      - pydantic-core==2.27.1
      - pydrive2==1.21.3
      - pyopenssl==24.2.1
      - regex==2024.11.6
      - requests-mock==1.12.1
      - restrictedpython==7.4
      - rsa==4.9
      - rstr==3.2.2
      - s3transfer==0.10.4
      - scikit-learn==1.5.2
      - semver==3.0.2
      - smart-open==7.1.0
      - split-folders==0.5.1
      - sqlalchemy==2.0.36
      - starlette==0.41.3
      - sympy==1.13.1
      - threadpoolctl==3.5.0
      - torchcam==0.4.0
      - torcheval==0.0.7
      - ujson==5.10.0
      - ultralytics-thop==2.0.13
      - uritemplate==4.1.1
      - uvicorn==0.32.1
      - websockets==14.1
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - xmljson==0.2.1
